version: '3.7'
services:
  mlflow-ui:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: sh ./docker/cmd.sh
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

    # Fix slow shutdown of web container
    # See: https://stackoverflow.com/a/62854251/1749551
    init: true
    volumes:
      - ..:/opt
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
      - ${JUPYTER_PORT}:${JUPYTER_PORT}

    # INFO: Following two lines are necessary for the backtrace by pdb
    stdin_open: true
    tty: true
